"""create tables

Revision ID: d5e12eee7f60
Revises: dba36e4f129e
Create Date: 2026-08-25 12:03:10.995032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5e12eee7f60'
down_revision: Union[str, None] = 'dba36e4f129e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('name'),
    schema='application'
    )
    op.create_index(op.f('ix_application_roles_role_id'), 'roles', ['role_id'], unique=False, schema='application')
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    schema='application'
    )
    op.create_index(op.f('ix_application_users_email'), 'users', ['email'], unique=True, schema='application')
    op.create_index(op.f('ix_application_users_user_id'), 'users', ['user_id'], unique=False, schema='application')
    op.create_table('agent_executions',
    sa.Column('execution_id', sa.Integer(), nullable=False),
    sa.Column('query_id', sa.String(), nullable=True),
    sa.Column('agent_name', sa.String(), nullable=True),
    sa.Column('input', sa.Text(), nullable=True),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('execution_id'),
    schema='audit'
    )
    op.create_index(op.f('ix_audit_agent_executions_execution_id'), 'agent_executions', ['execution_id'], unique=False, schema='audit')
    op.create_index(op.f('ix_audit_agent_executions_query_id'), 'agent_executions', ['query_id'], unique=False, schema='audit')
    op.create_table('decision_audits',
    sa.Column('decision_id', sa.Integer(), nullable=False),
    sa.Column('query_id', sa.String(), nullable=True),
    sa.Column('final_recommendation', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('decision_id'),
    schema='audit'
    )
    op.create_index(op.f('ix_audit_decision_audits_decision_id'), 'decision_audits', ['decision_id'], unique=False, schema='audit')
    op.create_index(op.f('ix_audit_decision_audits_query_id'), 'decision_audits', ['query_id'], unique=False, schema='audit')
    op.create_table('warehouses',
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('warehouse_id'),
    schema='inventory'
    )
    op.create_index(op.f('ix_inventory_warehouses_warehouse_id'), 'warehouses', ['warehouse_id'], unique=False, schema='inventory')
    op.create_table('machines',
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('rated_capacity_per_hour', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('utilization_percentage', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('machine_id'),
    schema='manufacturing'
    )
    op.create_index(op.f('ix_manufacturing_machines_machine_id'), 'machines', ['machine_id'], unique=False, schema='manufacturing')
    op.create_table('materials',
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('safety_stock_level', sa.Integer(), nullable=True),
    sa.Column('reorder_point', sa.Integer(), nullable=True),
    sa.Column('holding_cost_per_unit', sa.Float(), nullable=True),
    sa.Column('ordering_cost', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('material_id'),
    schema='manufacturing'
    )
    op.create_index(op.f('ix_manufacturing_materials_material_id'), 'materials', ['material_id'], unique=False, schema='manufacturing')
    op.create_table('production_lines',
    sa.Column('line_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('line_id'),
    schema='manufacturing'
    )
    op.create_index(op.f('ix_manufacturing_production_lines_line_id'), 'production_lines', ['line_id'], unique=False, schema='manufacturing')
    op.create_table('products',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_code', sa.String(), nullable=True),
    sa.Column('standard_cycle_time_min', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('product_id'),
    schema='manufacturing'
    )
    op.create_index(op.f('ix_manufacturing_products_product_code'), 'products', ['product_code'], unique=True, schema='manufacturing')
    op.create_index(op.f('ix_manufacturing_products_product_id'), 'products', ['product_id'], unique=False, schema='manufacturing')
    op.create_table('suppliers',
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('reliability_score', sa.Float(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('supplier_id'),
    schema='procurement'
    )
    op.create_index(op.f('ix_procurement_suppliers_supplier_id'), 'suppliers', ['supplier_id'], unique=False, schema='procurement')
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['application.roles.role_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['application.users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id'),
    schema='application'
    )
    op.create_table('tool_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('execution_id', sa.Integer(), nullable=True),
    sa.Column('tool_name', sa.String(), nullable=True),
    sa.Column('input', sa.Text(), nullable=True),
    sa.Column('output', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['execution_id'], ['audit.agent_executions.execution_id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='audit'
    )
    op.create_index(op.f('ix_audit_tool_executions_id'), 'tool_executions', ['id'], unique=False, schema='audit')
    op.create_table('inventory_stock',
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('quantity_on_hand', sa.Integer(), nullable=True),
    sa.Column('quantity_reserved', sa.Integer(), nullable=True),
    sa.Column('safety_stock', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['manufacturing.materials.material_id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['inventory.warehouses.warehouse_id'], ),
    sa.PrimaryKeyConstraint('stock_id'),
    schema='inventory'
    )
    op.create_index(op.f('ix_inventory_inventory_stock_stock_id'), 'inventory_stock', ['stock_id'], unique=False, schema='inventory')
    op.create_table('inventory_transactions',
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('transaction_type', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('transaction_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['manufacturing.materials.material_id'], ),
    sa.PrimaryKeyConstraint('transaction_id'),
    schema='inventory'
    )
    op.create_index(op.f('ix_inventory_inventory_transactions_transaction_id'), 'inventory_transactions', ['transaction_id'], unique=False, schema='inventory')
    op.create_table('bom_headers',
    sa.Column('bom_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['manufacturing.products.product_id'], ),
    sa.PrimaryKeyConstraint('bom_id'),
    schema='manufacturing'
    )
    op.create_index(op.f('ix_manufacturing_bom_headers_bom_id'), 'bom_headers', ['bom_id'], unique=False, schema='manufacturing')
    op.create_table('machine_maintenance',
    sa.Column('maintenance_id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=True),
    sa.Column('scheduled_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['manufacturing.machines.machine_id'], ),
    sa.PrimaryKeyConstraint('maintenance_id'),
    schema='manufacturing'
    )
    op.create_index(op.f('ix_manufacturing_machine_maintenance_maintenance_id'), 'machine_maintenance', ['maintenance_id'], unique=False, schema='manufacturing')
    op.create_table('work_orders',
    sa.Column('work_order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('planned_quantity', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['manufacturing.products.product_id'], ),
    sa.PrimaryKeyConstraint('work_order_id'),
    schema='manufacturing'
    )
    op.create_index(op.f('ix_manufacturing_work_orders_work_order_id'), 'work_orders', ['work_order_id'], unique=False, schema='manufacturing')
    op.create_table('customer_orders',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('requested_date', sa.DateTime(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['manufacturing.products.product_id'], ),
    sa.PrimaryKeyConstraint('order_id'),
    schema='orders'
    )
    op.create_index(op.f('ix_orders_customer_orders_order_id'), 'customer_orders', ['order_id'], unique=False, schema='orders')
    op.create_table('purchase_orders',
    sa.Column('po_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('expected_delivery_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['procurement.suppliers.supplier_id'], ),
    sa.PrimaryKeyConstraint('po_id'),
    schema='procurement'
    )
    op.create_index(op.f('ix_procurement_purchase_orders_po_id'), 'purchase_orders', ['po_id'], unique=False, schema='procurement')
    op.create_table('supplier_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('minimum_order_quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['manufacturing.materials.material_id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['procurement.suppliers.supplier_id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='procurement'
    )
    op.create_index(op.f('ix_procurement_supplier_materials_id'), 'supplier_materials', ['id'], unique=False, schema='procurement')
    op.create_table('bom_items',
    sa.Column('bom_item_id', sa.Integer(), nullable=False),
    sa.Column('bom_id', sa.Integer(), nullable=True),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('quantity_required', sa.Float(), nullable=True),
    sa.Column('scrap_percentage', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['bom_id'], ['manufacturing.bom_headers.bom_id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['manufacturing.materials.material_id'], ),
    sa.PrimaryKeyConstraint('bom_item_id'),
    schema='manufacturing'
    )
    op.create_index(op.f('ix_manufacturing_bom_items_bom_item_id'), 'bom_items', ['bom_item_id'], unique=False, schema='manufacturing')
    op.create_table('production_schedules',
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('work_order_id', sa.Integer(), nullable=True),
    sa.Column('machine_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['manufacturing.machines.machine_id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['manufacturing.work_orders.work_order_id'], ),
    sa.PrimaryKeyConstraint('schedule_id'),
    schema='manufacturing'
    )
    op.create_index(op.f('ix_manufacturing_production_schedules_schedule_id'), 'production_schedules', ['schedule_id'], unique=False, schema='manufacturing')
    op.create_table('purchase_order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=True),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('ordered_quantity', sa.Integer(), nullable=True),
    sa.Column('received_quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['manufacturing.materials.material_id'], ),
    sa.ForeignKeyConstraint(['po_id'], ['procurement.purchase_orders.po_id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='procurement'
    )
    op.create_index(op.f('ix_procurement_purchase_order_items_id'), 'purchase_order_items', ['id'], unique=False, schema='procurement')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_procurement_purchase_order_items_id'), table_name='purchase_order_items', schema='procurement')
    op.drop_table('purchase_order_items', schema='procurement')
    op.drop_index(op.f('ix_manufacturing_production_schedules_schedule_id'), table_name='production_schedules', schema='manufacturing')
    op.drop_table('production_schedules', schema='manufacturing')
    op.drop_index(op.f('ix_manufacturing_bom_items_bom_item_id'), table_name='bom_items', schema='manufacturing')
    op.drop_table('bom_items', schema='manufacturing')
    op.drop_index(op.f('ix_procurement_supplier_materials_id'), table_name='supplier_materials', schema='procurement')
    op.drop_table('supplier_materials', schema='procurement')
    op.drop_index(op.f('ix_procurement_purchase_orders_po_id'), table_name='purchase_orders', schema='procurement')
    op.drop_table('purchase_orders', schema='procurement')
    op.drop_index(op.f('ix_orders_customer_orders_order_id'), table_name='customer_orders', schema='orders')
    op.drop_table('customer_orders', schema='orders')
    op.drop_index(op.f('ix_manufacturing_work_orders_work_order_id'), table_name='work_orders', schema='manufacturing')
    op.drop_table('work_orders', schema='manufacturing')
    op.drop_index(op.f('ix_manufacturing_machine_maintenance_maintenance_id'), table_name='machine_maintenance', schema='manufacturing')
    op.drop_table('machine_maintenance', schema='manufacturing')
    op.drop_index(op.f('ix_manufacturing_bom_headers_bom_id'), table_name='bom_headers', schema='manufacturing')
    op.drop_table('bom_headers', schema='manufacturing')
    op.drop_index(op.f('ix_inventory_inventory_transactions_transaction_id'), table_name='inventory_transactions', schema='inventory')
    op.drop_table('inventory_transactions', schema='inventory')
    op.drop_index(op.f('ix_inventory_inventory_stock_stock_id'), table_name='inventory_stock', schema='inventory')
    op.drop_table('inventory_stock', schema='inventory')
    op.drop_index(op.f('ix_audit_tool_executions_id'), table_name='tool_executions', schema='audit')
    op.drop_table('tool_executions', schema='audit')
    op.drop_table('user_roles', schema='application')
    op.drop_index(op.f('ix_procurement_suppliers_supplier_id'), table_name='suppliers', schema='procurement')
    op.drop_table('suppliers', schema='procurement')
    op.drop_index(op.f('ix_manufacturing_products_product_id'), table_name='products', schema='manufacturing')
    op.drop_index(op.f('ix_manufacturing_products_product_code'), table_name='products', schema='manufacturing')
    op.drop_table('products', schema='manufacturing')
    op.drop_index(op.f('ix_manufacturing_production_lines_line_id'), table_name='production_lines', schema='manufacturing')
    op.drop_table('production_lines', schema='manufacturing')
    op.drop_index(op.f('ix_manufacturing_materials_material_id'), table_name='materials', schema='manufacturing')
    op.drop_table('materials', schema='manufacturing')
    op.drop_index(op.f('ix_manufacturing_machines_machine_id'), table_name='machines', schema='manufacturing')
    op.drop_table('machines', schema='manufacturing')
    op.drop_index(op.f('ix_inventory_warehouses_warehouse_id'), table_name='warehouses', schema='inventory')
    op.drop_table('warehouses', schema='inventory')
    op.drop_index(op.f('ix_audit_decision_audits_query_id'), table_name='decision_audits', schema='audit')
    op.drop_index(op.f('ix_audit_decision_audits_decision_id'), table_name='decision_audits', schema='audit')
    op.drop_table('decision_audits', schema='audit')
    op.drop_index(op.f('ix_audit_agent_executions_query_id'), table_name='agent_executions', schema='audit')
    op.drop_index(op.f('ix_audit_agent_executions_execution_id'), table_name='agent_executions', schema='audit')
    op.drop_table('agent_executions', schema='audit')
    op.drop_index(op.f('ix_application_users_user_id'), table_name='users', schema='application')
    op.drop_index(op.f('ix_application_users_email'), table_name='users', schema='application')
    op.drop_table('users', schema='application')
    op.drop_index(op.f('ix_application_roles_role_id'), table_name='roles', schema='application')
    op.drop_table('roles', schema='application')
    # ### end Alembic commands ###
